language: node_js
node_js:
  - "10"
install:
  - npm install
branches:
  only:
    - master
script:
  - mkdir output
  - wget http://203.104.209.102/kcs2/js/main.js
  - npx js-beautify main.js -o output/main.formated.js
  - cat output/main.formated.js | grep -o 'PORT_API_SEED = \[.*\]'
deploy:
  provider: pages
  name: kozora
  email: kozora@hotmail.com
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: output
  on:
    branch: master
